version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "test-stack"
s3_bucket = "saifu-codesam"
s3_prefix = "sam-app-artifacts"
region = "us-east-1"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
github_owner = "saifudheenvk"
github_repo = "sam-codepipeline-test"
github_branch = "master"
image_repository = ""
image_repositories = []


[dev]
[dev.deploy]
[dev.deploy.parameters]
stack_name = "test-stack"
s3_prefix = "dev-sam-app-artifacts"
github_owner = "dev-owner"
github_branch = "master"

[dev.sync]
[dev.sync.parameters]
stack_name = "test-stack"
watch = true

[prod]
[prod.deploy]
[prod.deploy.parameters]
stack_name = "prod-test-stack"
s3_prefix = "prod-sam-app-artifacts"
github_branch = "master"
region = "us-west-2"
