version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "test-stack"
s3_bucket = "saifu-codesam"
s3_prefix = "sam-app"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"

